eureka:
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:  port: 8762
spring:  application:    name: zuul-server
zuul:#  ignored-services: '*'
  routes:
   user-service:
      path: /user/**
      service-id: user-service
   media-service:
     path: /media/**
     service-id: media-service
     stripPrefix: false
   miscellaneous-service:
      path: /misc/**
      service-id: miscellaneous-service

logging:  level:   org:
    springframework: debug                                           